version: "3"
services:
  router-example:
    image: node:16-alpine
    environment:
      REACT_APP_API: https://reqres.in
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - '3000:3000'
    entrypoint: ["yarn", "start"]
